Sympy variables are created using unique string identifiers.

In [1]:
import sympy as sp
import numpy as np
x = sp.Symbol("x")
y = sp.Symbol("y")
z = sp.Symbol("z")

One can form expression from symbols.
Sympy expressions are made up of numbers, symbols, and sympy functions.

In [2]:
expression = x**2. + y**2. + z ** 2.
expression

x**2.0 + y**2.0 + z**2.0

Two expressions may be added together to form a new one.

In [3]:
other_expression = x**2.
expression += other_expression
expression

2*x**2.0 + y**2.0 + z**2.0

One can form sympy `Matrix` objects.

In [4]:
sp.Matrix([[1,2],[3,4]])

Matrix([
[1, 2],
[3, 4]])

An important `Matrix` function is `eye(n)`, which forms a $n \times n$ identity matrix.

In [5]:
sp.eye(3)

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

One can stuff expressions into matrices, too.

In [6]:
# One can stuff expressions into matrices
f1 = x**2.+y**2-z**2.
f2 = 2*x + y + z
function_matrix = sp.Matrix([f1,f2])
function_matrix

Matrix([
[x**2.0 + y**2 - z**2.0],
[           2*x + y + z]])

One may compute the Jacobian of vector valued functions, too.

In [7]:
function_matrix.jacobian([x,y,z]) # pass in a list of Sympy Symbols to take the Jacobian

Matrix([
[2.0*x**1.0, 2*y, -2.0*z**1.0],
[         2,   1,           1]])

Sympy expressions can be evaluated by passing in a Python dictionary mapping Symbol `Symbol`s to specific values.

In [8]:
x_val = 1.0
y_val = 2.0
z_val = 3.0
values={"x":x_val,"y":y_val,"z":z_val}
f1.subs(values)

-4.00000000000000

One can even valuate the Jacobian of functions.

In [9]:
J_mat = function_matrix.jacobian([x,y,z]).subs(values)
J_mat

Matrix([
[2.0, 4.0, -6.0],
[  2,   1,    1]])

To convert a Sympy `Matrix` into a Numpy array, one may use the following:

In [10]:
np.array(J_mat)

array([[2.00000000000000, 4.00000000000000, -6.00000000000000],
       [2, 1, 1]], dtype=object)

After evaluating an expression in Sympy, the return type is a `sympy.Float`.
However, this is not readily usable by Numpy. Therefore, consider casting `sympy.Float` to a `numpy.float64`.

In [11]:
J=np.array(J_mat).astype(np.float64)
J

array([[ 2.,  4., -6.],
       [ 2.,  1.,  1.]])

At this point, one cna do all the usual stuff one would in Numpy.

In [12]:
J.T@J

array([[  8.,  10., -10.],
       [ 10.,  17., -23.],
       [-10., -23.,  37.]])